services:
  # ASP.NET Core Application
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:4.0-management  # Official RabbitMQ image with management plugin
    ports:
      - "5672:5672"  # Default RabbitMQ port
      - "15672:15672" # Management interface port
    networks:
      - my-network
  api:
    build:
        dockerfile: ApiMensagery/apimensagery:dev            
    depends_on:
      - rabbitmq
    networks:
      - my-network  
networks:
  my-network:
    driver: bridge
  


